'use client';

import { useState } from 'react';
import Image from 'next/image';
import { Alert, Button, Input, Label, Spinner } from '@inventory-system/ui';
import { getErrorMessage } from '@/lib/api/client';
import { useConfirmTwoFactor, type TwoFactorEnrollment } from '../../security-queries';

/** Shown once, between starting enrollment and confirming the first authenticator code. */
export const TwoFactorEnrollmentPanel = ({
    enrollment,
    onCancel,
    onConfirmed,
}: {
    enrollment: TwoFactorEnrollment;
    onCancel: () => void;
    onConfirmed: () => void;
}) => {
    const [code, setCode] = useState('');
    const confirm = useConfirmTwoFactor();

    return (
        <div className="space-y-4 rounded-xl border border-slate-700 bg-slate-950/40 p-5">
            <div className="flex flex-col gap-5 sm:flex-row">
                <Image
                    src={enrollment.qrCode}
                    alt="Authenticator enrollment QR code"
                    width={220}
                    height={220}
                    unoptimized
                    className="h-[220px] w-[220px] rounded-lg bg-white p-2"
                />
                <div className="min-w-0 flex-1">
                    <p className="font-medium text-white">Scan this code</p>
                    <p className="mt-2 text-sm leading-6 text-slate-400">
                        Then enter the six-digit code generated by your authenticator. If scanning
                        is unavailable, copy the setup URI below.
                    </p>
                    <code className="mt-3 block break-all rounded bg-slate-950 p-2 text-xs text-slate-400">
                        {enrollment.totpURI}
                    </code>
                </div>
            </div>
            {confirm.error && <Alert variant="danger">{getErrorMessage(confirm.error)}</Alert>}
            <div className="space-y-1.5">
                <Label htmlFor="enrollment-code">Authenticator code</Label>
                <Input
                    id="enrollment-code"
                    className="max-w-xs font-mono tracking-widest"
                    value={code}
                    onChange={(event) => setCode(event.target.value)}
                    autoComplete="one-time-code"
                />
            </div>
            <div className="flex gap-3">
                <Button
                    type="button"
                    disabled={confirm.isPending || !code.trim()}
                    onClick={() => confirm.mutate(code, { onSuccess: onConfirmed })}
                >
                    {confirm.isPending && <Spinner size={4} className="mr-2" />} Confirm setup
                </Button>
                <Button type="button" variant="ghost" onClick={onCancel}>
                    Cancel
                </Button>
            </div>
        </div>
    );
};
